### ISSUE TITLE
Publish datasets on HuggingFace

### ISSUE THREAD

**Issue by flaviusburca** [OpenLLM-Ro/llama-recipes#2]
Are the actual datasets open-source ? Will they be published on HuggingFace ?

**Comment by trebedea** [comment]
We will publish the datasets as well in the following 2-3 weeks.
Right now the focus is to release a `Ro-Mistral-7b-Intstruct` with a substantial improvement over `Ro-Llama2-7b` using the same recipe and datasets.

**Comment by rennokki** [comment]
@trebedea Are the training datasets mainly a RO sub-split of the actual datasets that contain multi-lingual data on which Llama-2 was trained on + some others? If so, any idea if a Llama-3 is on the road?

**Comment by trebedea** [comment]
We do open research, so the technical report including datasets used for training and finetuning is public: 
https://arxiv.org/abs/2405.07703

Our main aim is to identify a "recipe" which allows improvement of any generic LLM, meaning also Mistral / Mixtral or Llama-3. Right now we have promising results showing that Mistral-7B can be improved using the current "recipe".

Current recipe is (on short, detailed in the paper / technical report):
- continual pre-training on Romanian data from CulturaX dataset (with some curation / filtering for quality)
- instruct & chat fine-tuning using open datasets translated in Romanian

Hope this makes sense.

**Comment by rennokki** [comment]
@trebedea Yes, it does. Thanks! 👍🏼

**Comment by MihaiMasala** [comment]
The translated datasets are now available on [HF](https://huggingface.co/collections/OpenLLM-Ro/sft-datasets-667ed0a0508e393e7c6e4d2c).
